default: &default
  adapter: postgresql
  host: db
  pool: 5
  timeout: 5000
  user: postgres
  password:

development:
  <<: *default
  database: super_imap_development

stress:
  <<: *default
  database: super_imap_stress

test:
  <<: *default
  database: super_imap_test
